spring:
  resources:
    cache:
      period: 0
    static-locations: file:./client/,file:./client/ext/classic/locale/overrides/de/
  jpa:
    show-sql: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
    timeout: 480m

server:
  port: 8080
  compression:
    enabled: false

springdoc:
  swagger-ui:
    with-credentials: true

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
    org.apache: INFO
    liquibase: INFO
    ch: INFO